/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vmjujdhuygaacjjzjdlw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtanVqZGh1eWdhYWNqanpqZGx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxNjY1NjgsImV4cCI6MjA5OTc0MjU2OH0.d-8829cIfHbJ7cbu7Y2-v5hh9IpyMO9JQyq6ZqCQwnk"